/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillTreeRouteImport } from './routes/skill-tree'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobBoardRouteImport } from './routes/job-board'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'

const SkillTreeRoute = SkillTreeRouteImport.update({
  id: '/skill-tree',
  path: '/skill-tree',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobBoardRoute = JobBoardRouteImport.update({
  id: '/job-board',
  path: '/job-board',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/job-board': typeof JobBoardRoute
  '/login': typeof LoginRoute
  '/roadmap': typeof RoadmapRoute
  '/skill-tree': typeof SkillTreeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/job-board': typeof JobBoardRoute
  '/login': typeof LoginRoute
  '/roadmap': typeof RoadmapRoute
  '/skill-tree': typeof SkillTreeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/job-board': typeof JobBoardRoute
  '/login': typeof LoginRoute
  '/roadmap': typeof RoadmapRoute
  '/skill-tree': typeof SkillTreeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/achievements' | '/job-board' | '/login' | '/roadmap' | '/skill-tree'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/achievements' | '/job-board' | '/login' | '/roadmap' | '/skill-tree'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/job-board'
    | '/login'
    | '/roadmap'
    | '/skill-tree'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  JobBoardRoute: typeof JobBoardRoute
  LoginRoute: typeof LoginRoute
  RoadmapRoute: typeof RoadmapRoute
  SkillTreeRoute: typeof SkillTreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skill-tree': {
      id: '/skill-tree'
      path: '/skill-tree'
      fullPath: '/skill-tree'
      preLoaderRoute: typeof SkillTreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-board': {
      id: '/job-board'
      path: '/job-board'
      fullPath: '/job-board'
      preLoaderRoute: typeof JobBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  JobBoardRoute: JobBoardRoute,
  LoginRoute: LoginRoute,
  RoadmapRoute: RoadmapRoute,
  SkillTreeRoute: SkillTreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
